# Clipboard Stack Trace Cleaner Configuration
# This file contains default configuration values for the no-reaction application

# Clipboard monitoring settings
clipboard-polling-interval: 500ms
clipboard-max-content-size: 1048576

# Output and logging settings
verbose: false
log-file: ""
show-timestamp: true
quiet: false

# Parser settings
parser-min-stack-lines: 2
parser-min-stack-trace-length: 20
parser-custom-patterns: []

# Application settings
config-file: config.yaml
