# TraceTrim Configuration
# This file contains default configuration values for the TraceTrim application

# Clipboard monitoring settings
clipboard-polling-interval: 500ms
clipboard-max-content-size: 1048576

# Output and logging settings
verbose: false
log-file: ""
show-timestamp: true
quiet: false

# Parser settings
parser-min-stack-lines: 2
parser-min-stack-trace-length: 20
parser-custom-patterns: []

# Script mode flag (simplified)
script-mode: false

# Auto-detect script mode based on environment
auto-detect-script-mode: true

# Application settings
config-file: config.yaml
